# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce9913078c1727a4196bb37b8b6c3cf0e27d41e852b26d163b983ff4fa092a5eb65c4df91ace66298f14947d8a89b5c3aec2dfdf20b308ca28e4d88068dc34a2

test:
  secret_key_base: 6386e10e67250054ba9c312d205d41a99554a3d2d4304452310811282f92f751f1d5c6a95d56c51d181c0fa188bf59e373bab5f94dd262f7057efb8cf41c1cba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
